#!/bin/bash

# Budget Alerts and Warnings Script
# Version: 1.0.0
# Purpose: Monitor usage against budget thresholds and send alerts

set -e

# Configuration
CONFIG_FILE="scripts/config-tracking.json"
USAGE_FILE="CLAUDE_USAGE.md"
ALERTS_LOG="logs/budget-alerts.log"

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Ensure logs directory exists
mkdir -p logs

# Function to log alerts
log_alert() {
    local level=$1
    local message=$2
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$timestamp] [$level] $message" >> "$ALERTS_LOG"
}

# Function to get budget from config
get_budget() {
    local period=$1
    if [ -f "$CONFIG_FILE" ]; then
        jq -r ".budget.$period // 0" "$CONFIG_FILE"
    else
        echo "0"
    fi
}

# Function to get current usage for period
get_period_usage() {
    local period=$1
    local current_date=$(date '+%Y-%m-%d')
    local start_date=""

    case $period in
        "daily")
            start_date=$(date '+%Y-%m-%d')
            ;;
        "weekly")
            start_date=$(date -d '7 days ago' '+%Y-%m-%d')
            ;;
        "monthly")
            start_date=$(date -d '30 days ago' '+%Y-%m-%d')
            ;;
        "quarterly")
            start_date=$(date -d '90 days ago' '+%Y-%m-%d')
            ;;
        *)
            echo "0.00"
            return
            ;;
    esac

    # Parse CLAUDE_USAGE.md for usage in date range
    if [ -f "$USAGE_FILE" ]; then
        awk -v start="$start_date" -v end="$current_date" '
        /^\| [0-9]{4}-[0-9]{2}-[0-9]{2} \|/ {
            # Extract date and cost
            match($0, /\| ([0-9]{4}-[0-9]{2}-[0-9]{2}) \|.*\| \$([0-9.]+) \|/, arr)
            if (arr[1] >= start && arr[1] <= end) {
                sum += arr[2]
            }
        }
        END {
            printf "%.4f", sum
        }
        ' "$USAGE_FILE"
    else
        echo "0.00"
    fi
}

# Function to calculate percentage
calculate_percentage() {
    local usage=$1
    local budget=$2
    if [ "$(echo "$budget > 0" | bc)" -eq 1 ]; then
        echo "scale=2; ($usage / $budget) * 100" | bc
    else
        echo "0"
    fi
}

# Function to send alert
send_alert() {
    local level=$1
    local period=$2
    local percentage=$3
    local usage=$4
    local budget=$5

    local color=$GREEN
    local emoji="✅"

    case $level in
        "CRITICAL")
            color=$RED
            emoji="🚨"
            ;;
        "WARNING")
            color=$YELLOW
            emoji="⚠️"
            ;;
        "INFO")
            color=$BLUE
            emoji="ℹ️"
            ;;
    esac

    echo -e "${color}${emoji} [$level] ${period^^} BUDGET ALERT${NC}"
    echo -e "  Usage: \$${usage} / \$${budget} (${percentage}%)"
    echo ""

    log_alert "$level" "${period} budget at ${percentage}% (\$${usage}/\$${budget})"
}

# Function to create GitHub issue for critical alerts
create_budget_issue() {
    local period=$1
    local percentage=$2
    local usage=$3
    local budget=$4

    local title="🚨 Budget Alert: ${period^^} usage at ${percentage}%"
    local body="## Budget Alert

**Period:** ${period^^}
**Current Usage:** \$${usage}
**Budget Limit:** \$${budget}
**Percentage:** ${percentage}%

### Action Required

The ${period} Claude API usage has reached ${percentage}% of the allocated budget.

### Recommendations

1. Review recent high-cost operations in \`CLAUDE_USAGE.md\`
2. Consider optimizing prompts and reducing token usage
3. Evaluate if budget increase is necessary
4. Review cost optimization suggestions

### Next Steps

- [ ] Review usage patterns
- [ ] Implement cost optimizations
- [ ] Adjust budget if needed
- [ ] Monitor for next 24 hours

---
*Auto-generated by Budget Alert System*
*Time: $(date '+%Y-%m-%d %H:%M:%S')*
"

    # Only create issue if gh CLI is available and we're in GitHub Actions
    if command -v gh &> /dev/null && [ -n "$GITHUB_REPOSITORY" ]; then
        gh issue create \
            --title "$title" \
            --body "$body" \
            --label "cost-alert,automated" \
            --assignee "@me" 2>/dev/null || echo "  (Issue creation skipped - not in GitHub environment)"
    fi
}

# Main monitoring function
monitor_budgets() {
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}Budget Monitoring System${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    # Check if alerts are enabled
    if [ -f "$CONFIG_FILE" ]; then
        ALERTS_ENABLED=$(jq -r '.alerts.enabled // true' "$CONFIG_FILE")
        if [ "$ALERTS_ENABLED" != "true" ]; then
            echo -e "${YELLOW}Budget alerts are disabled in config${NC}"
            return
        fi
    fi

    # Monitor each period
    for period in daily weekly monthly quarterly; do
        local budget=$(get_budget "$period")
        local usage=$(get_period_usage "$period")

        if [ "$(echo "$budget > 0" | bc)" -eq 1 ]; then
            local percentage=$(calculate_percentage "$usage" "$budget")
            local threshold_hit=""

            echo -e "${BLUE}${period^^} Budget Check:${NC}"
            echo -e "  Budget: \$${budget}"
            echo -e "  Usage:  \$${usage}"
            echo -e "  Status: ${percentage}%"

            # Check thresholds
            if [ "$(echo "$percentage >= 100" | bc)" -eq 1 ]; then
                send_alert "CRITICAL" "$period" "$percentage" "$usage" "$budget"
                create_budget_issue "$period" "$percentage" "$usage" "$budget"
            elif [ "$(echo "$percentage >= 95" | bc)" -eq 1 ]; then
                send_alert "CRITICAL" "$period" "$percentage" "$usage" "$budget"
            elif [ "$(echo "$percentage >= 90" | bc)" -eq 1 ]; then
                send_alert "WARNING" "$period" "$percentage" "$usage" "$budget"
            elif [ "$(echo "$percentage >= 75" | bc)" -eq 1 ]; then
                send_alert "WARNING" "$period" "$percentage" "$usage" "$budget"
            elif [ "$(echo "$percentage >= 50" | bc)" -eq 1 ]; then
                send_alert "INFO" "$period" "$percentage" "$usage" "$budget"
            else
                echo -e "  ${GREEN}✓ Within budget${NC}"
            fi
            echo ""
        fi
    done

    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

# Run monitoring
monitor_budgets

# Exit with appropriate code
exit 0
